witwassen:
  npc:
    name: "Witwasser"

  npc-locations:

  launder-locations:

  alert-chance: 30 # procent
  launder-radius: 5
  launder-delay: 300 # seconden

  items:
    dirty-money:
      name: "&cDirty Money"
      lore:
        - "&7Illegaal verkregen geld"
      material: PAPER

    clean-money:
      name: "&aClean Money"
      lore:
        - "&7Witgewassen geld"
      material: PAPER

kraken:
  npc:
    name: "Kraker"

  npc-locations:

  launder-locations:

  alert-chance: 30 # procent
  kraak-radius: 2
  kraak-delay: 300 # seconden

messages:
  no-dirty-money: "&cJe hebt geen dirty money in je hand."
  go-to-location: "&aGa naar deze locatie om te witwassen: %x%, %y%, %z%"
  not-close-enough: "&cJe bent niet op de juiste locatie!"
  success: "&aJe hebt succesvol je geld witgewassen!"
  alert: "&cVerdachte witwasactiviteit bij %location%"
  gui:
    open: "&aBinnenkort wordt een GUI geopend."
    add-launder: "&aJe huidige locatie is toegevoegd als launder locatie."
    add-kraak: "&aJe huidige locatie is toegevoegd als kraak locatie."
    spawn-npc: "&aDe nieuwe Witwasser NPC is geplaatst!"
    launder-delete: "&cLaunder locatie &4%slot% &cis verwijderd."
    launder-tp: "&aJe bent geteleporteerd naar launder locatie #%slot%."
    npc-tp: "&aJe bent geteleporteerd naar NPC locatie #%slot%."
    npc-delete: "&cNPC op slot &4#%slot% &cis verwijderd."
  kraak:
    start: "&cHet kraken is gestart..."
    spawn-npc: "&aDe nieuwe Kraker NPC is geplaatst!"