name: MTW-Witwas
version: '1.0-SNAPSHOT'
main: nl.alwayslucky.mtwwitwas.Main
softdepend: [Citizens]
commands:
  witwas:
    usage: /witwas give <dirty|clean>
    description: Geef jezelf een money item
